### ISSUE TITLE
Unable to run the manual assistant

### ISSUE THREAD

**Issue by hamidtirmizi** [nneonneo/threes-ai#16]
I have been getting error and haven't been able to run this. Could you please write a step by step for python novices?

$ python manual_assistant.py 
Traceback (most recent call last):
  File "manual_assistant.py", line 9, in <module>
    from base_assistant import run_assistant, movenames
  File "/Users/hamid/Desktop/threes-ai-prebuilt-linux-x86_64/base_assistant.py", line 6, in <module>
    from threes_ai_c import find_best_move, set_heurweights
  File "/Users/hamid/Desktop/threes-ai-prebuilt-linux-x86_64/threes_ai_c.py", line 10, in <module>
    threes = ctypes.CDLL(dllfn)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(bin/threes.so, 6): no suitable image found.  Did find:
	bin/threes.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/hamid/Desktop/threes-ai-prebuilt-linux-x86_64/bin/threes.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

**Comment by nneonneo** [comment]
You’re on macOS but trying to use Linux prebuilt binaries, which won’t
work. Try to find some macOS binaries or build it yourself following the
install instructions.
