### ISSUE TITLE
ShellCommandException when trying to use android assistant

### ISSUE THREAD

**Issue by Kooludo** [nneonneo/threes-ai#7]
Hiya. Thanks for this, it looks brilliant! I'm having a problem getting the Android assistant to work. I've set up the ocr.py for my device (Samsung Galaxy S6 - I'll send a PR if I get it working) and recorded the swipe events as per the readme (`python -m android.inputemu --record up down left right`)but I get an error when trying to send the swipe command to the device. This is the stacktrace:

```
Move number 1
[[  0   0   0   3]
 [192   2   6   1]
 [  1   3   2   3]
 [  1   1   3   3]]
Current score: 2211
Next tile: [1] (deck=1:1, 2:3, 3:2)
Traceback (most recent call last):
  File "android_assistant.py", line 144, in <module>
    exit(main(sys.argv[1:]))
  File "android_assistant.py", line 140, in main
    run_assistant(assistant.gen_board_mem(), assistant.make_move, args.from_start)
  File "/threes/threes-ai/base_assistant.py", line 136, in run_assistant
    make_move_func(movenames[move])
  File "android_assistant.py", line 68, in make_move
    playback_gesture(self.shell, self.ident, move)
  File "/threes/threes-ai/android/inputemu.py", line 75, in playback_gesture
    _write_events(shell, pack)
  File "/threes/threes-ai/android/inputemu.py", line 44, in _write_events
    shell.execute("echo -ne '%s' > %s" % (s, dev))
  File "/threes/threes-ai/android/adb_shell.py", line 455, in execute
    raise ShellCommandException(self._encode_command(cmd), int(d['status']), ret.decode())
android.adb_shell.ShellCommandException: Command 'echo -ne '\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x39\x00\xd8\x1f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x4a\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x45\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x35\x00\xb1\x09\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x36\x00\xc3\x0a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x30\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x31\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' > /dev/input/event1' returned non-zero exit status 1
```

If I set a debugger I see that the value of `d` is `{'status': bytearray(b'1'), 'hash': bytearray(b'$'), 'user': bytearray(b'shell'), 'cwd': bytearray(b'/')}`

I'm on Python 2.7.10. I know nothing about Android dev. Any clues on how to debug this would be appreciated.

Many thanks.

**Comment by nneonneo** [comment]
Hmm, this is odd. Normally the shell does have write access to the `/dev/input/event` streams.

Can you show me the recorded events (from the `events` directory)? Also useful would be the output of the following commands:

```
adb shell id
adb shell getevent
adb shell ls -la /dev/input
```

For `adb shell getevent` just kill the program (press Ctrl+C) after it prints out the initial information.

**Comment by Kooludo** [comment]
Thanks for such a speedy response!

Recorded events:
[down.txt](https://github.com/nneonneo/threes-ai/files/169549/down.txt)
[left.txt](https://github.com/nneonneo/threes-ai/files/169548/left.txt)
[right.txt](https://github.com/nneonneo/threes-ai/files/169550/right.txt)
[up.txt](https://github.com/nneonneo/threes-ai/files/169547/up.txt)

```
$ adb shell id
uid=2000(shell) gid=2000(shell) groups=1003(graphics),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats) context=u:r:shell:s0
```

```
$ adb shell getevent
add device 1: /dev/input/event14
  name:     "ssp_context"
add device 2: /dev/input/event13
  name:     "meta_event"
add device 3: /dev/input/event12
  name:     "interrupt_gyro_sensor"
add device 4: /dev/input/event11
  name:     "step_cnt_sensor"
add device 5: /dev/input/event10
  name:     "sig_motion_sensor"
add device 6: /dev/input/event9
  name:     "gesture_sensor"
add device 7: /dev/input/event8
  name:     "temp_humidity_sensor"
add device 8: /dev/input/event7
  name:     "grip_sensor"
add device 9: /dev/input/event6
  name:     "proximity_sensor"
add device 10: /dev/input/event5
  name:     "light_ir_sensor"
add device 11: /dev/input/event4
  name:     "light_sensor"
add device 12: /dev/input/event3
  name:     "hrmled_sensor"
add device 13: /dev/input/event2
  name:     "hrm_sensor"
add device 14: /dev/input/event18
  name:     "certify_hall"
add device 15: /dev/input/event1
  name:     "sec_touchscreen"
add device 16: /dev/input/event17
  name:     "hall"
add device 17: /dev/input/event16
  name:     "gpio_keys.30"
add device 18: /dev/input/event15
  name:     "Headset"
add device 19: /dev/input/event0
  name:     "sec_touchkey"
```

```
$ adb shell ls -la /dev/input
crw-rw---- root     input     13,  64 2016-03-08 16:27 event0
crw-rw---- root     input     13,  65 2016-03-08 16:27 event1
crw-rw---- root     input     13,  74 2016-03-08 16:27 event10
crw-rw---- root     input     13,  75 2016-03-08 16:27 event11
crw-rw---- root     input     13,  76 2016-03-08 16:27 event12
crw-rw---- root     input     13,  77 2016-03-08 16:27 event13
crw-rw---- root     input     13,  78 2016-03-08 16:27 event14
crw-rw---- root     input     13,  79 2016-03-08 16:27 event15
crw-rw---- root     input     13,  80 2016-03-08 16:27 event16
crw-rw---- root     input     13,  81 2016-03-08 16:27 event17
crw-rw---- root     input     13,  82 2016-03-08 16:27 event18
crw-rw---- root     input     13,  66 2016-03-08 16:27 event2
crw-rw---- root     input     13,  67 2016-03-08 16:27 event3
crw-rw---- root     input     13,  68 2016-03-08 16:27 event4
crw-rw---- root     input     13,  69 2016-03-08 16:27 event5
crw-rw---- root     input     13,  70 2016-03-08 16:27 event6
crw-rw---- root     input     13,  71 2016-03-08 16:27 event7
crw-rw---- root     input     13,  72 2016-03-08 16:27 event8
crw-rw---- root     input     13,  73 2016-03-08 16:27 event9
```

Let me know if I can provide anything else. I'm on Ubuntu 15.10 btw.

**Comment by Kooludo** [comment]
Ooops, pressed wrong button to close issue.

**Comment by nneonneo** [comment]
Interesting. This all looks normal and fine. One more test: can you do `adb shell`, and at the prompt enter this command:

```
echo -ne '\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x39\x00\xd8\x1f\x00\x00' > /dev/input/event1
```

and then this one:

```
echo -ne '\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x39\x00\xd8\x1f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x4a\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x45\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x35\x00\xb1\x09\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x36\x00\xc3\x0a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x30\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x31\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' > /dev/input/event1
```

and show the terminal output (including the following prompt).

**Comment by Kooludo** [comment]
First:

```
$ adb shell
x00\x00\x00\x03\x00\x39\x00\xd8\x1f\x00\x00' > /dev/input/event1              <
1|shell@zeroflte:/ $ 
```

Second:

```
$ adb shell
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' > /dev/input/event1                <
1|shell@zeroflte:/ $ 
```

One after the other without restarting `adb shell`:

```
$ adb shell
x00\x00\x00\x03\x00\x39\x00\xd8\x1f\x00\x00' > /dev/input/event1              <
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' > /dev/input/event1              <
1|shell@zeroflte:/ $ 
```

**Comment by nneonneo** [comment]
Sorry for the crazy back-and-forth. Still trying to figure out what's going on. I think I have a better idea...

In `adb shell`, try (all at once is fine)

```
echo 'Hello'
echo -n 'Hello'
echo -e 'Hello'
echo -ne 'Hello'
echo -ne '\x48\x65\x6c\x6c\x6f'
```

**Comment by Kooludo** [comment]
No probs - I really appreciate the help!

```
$ adb shell
shell@zeroflte:/ $ echo 'Hello'
Hello
shell@zeroflte:/ $ echo -n 'Hello'
Helloshell@zeroflte:/ $ echo -e 'Hello'
Hello
shell@zeroflte:/ $ echo -ne 'Hello'
Helloshell@zeroflte:/ $ echo -ne '\x48\x65\x6c\x6c\x6f'
Helloshell@zeroflte:/ $ 
```

**Comment by nneonneo** [comment]
So it looks like it can't write to the `/dev/input/event1`...that's weird because you do have the right permissions. Is the device rooted?

Try

```
sendevent /dev/input/event1 3 57 8154
sendevent /dev/input/event1 1 330 1
sendevent /dev/input/event1 1 325 1
sendevent /dev/input/event1 3 53 2723
sendevent /dev/input/event1 3 54 2254
sendevent /dev/input/event1 3 48 4
sendevent /dev/input/event1 3 49 3
sendevent /dev/input/event1 0 0 0
```

in `adb shell`.

**Comment by Kooludo** [comment]
```
$ adb shell
shell@zeroflte:/ $ sendevent /dev/input/event1 3 57 8154
shell@zeroflte:/ $ sendevent /dev/input/event1 1 330 1
shell@zeroflte:/ $ sendevent /dev/input/event1 1 325 1
shell@zeroflte:/ $ sendevent /dev/input/event1 3 53 2723
shell@zeroflte:/ $ sendevent /dev/input/event1 3 54 2254
shell@zeroflte:/ $ sendevent /dev/input/event1 3 48 4
shell@zeroflte:/ $ sendevent /dev/input/event1 3 49 3
shell@zeroflte:/ $ sendevent /dev/input/event1 0 0 0
shell@zeroflte:/ $ 
```

I did root it, but then I believe it was unrooted with an upgrade and I haven't re done it since.

**Comment by nneonneo** [comment]
Huh, so `sendevent` seems to work. Cool, that means that we can just use `sendevent` if `echo` fails. Can you edit your `inputemu.py`, `_write_events` function to read

```
def _write_events(shell, events):
    for dev, type, value, code in events:
        shell.execute('sendevent %s %d %d %d' % (dev, type, value, code))
    return
```

If this works I'll gin up a patch to pick `sendevent` if `echo` fails.

(I've been using `echo` because it's faster than `sendevent`, but hey, if `sendevent` is the only option then we'll take it!)

**Comment by Kooludo** [comment]
Ah that's amazing! Thanks so much for helping with this! :)

**Comment by Kooludo** [comment]
It works! That's brilliant, didn't expect such quick help :) Thanks loads :)

**Comment by nneonneo** [comment]
Just pushed a new patch - would appreciate it if you could test that to make sure it still works.

**Comment by Kooludo** [comment]
All works fine for me. Thanks once again for your help. :)
